version: '3.4'
services:
  database:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=1073741824
    environment:
      - MYSQL_ROOT_PASSWORD=bananas
      - MYSQL_DATABASE=api
    ports:
      - 3306:3306
    networks:
      - yts

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports: ['127.0.0.1:9200:9200']
    networks: ['yts']

networks:
  yts:
